apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: inventory-service
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30001