
name: Order-Inventory services

services:
 inventory:
   image: vinayk101/inventory-service:v1
   container_name: inventory_service
   ports:
     - "8082:8082"
   networks:
     - internal_network

 order:
   image: vinayk101/order-service:v1
   container_name: order_service
   ports:
     - "8080:8080"
   networks:
     - internal_network

networks:
 internal_network:
   driver: bridge