apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: dev
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
  type: NodePort