apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: stage
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: vinayk101/inventory-service:v1
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: inventory-config