apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: bXlzcWwxMjM= # Base64 encoded value of 'mysql123'
  mysql-password: bXlzcWwxMjM= # Base64 encoded value of 'mysql123'